# Generated by Django 5.0.6 on 2026-06-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=255, verbose_name='Familiyasi')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefon')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(related_name='students', to='courses.group', verbose_name='Guruhi')),
            ],
        ),
    ]
