# Generated by Django 5.0.6 on 2026-06-09 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="To'lov summasi")),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('online', 'Humo / Payme / Apelsin')], default='cash', max_length=20, verbose_name="To'lov usuli")),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name="To'langan vaqti")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student', verbose_name="O'quvchi")),
            ],
        ),
    ]
