# Generated by Django 5.0.6 on 2026-06-09 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kurs nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Kurs haqida...')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kurs narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Guruh nomi')),
                ('teacher_name', models.CharField(max_length=255, verbose_name="Guruh o'qituvchisi")),
                ('lesson_started', models.TimeField(verbose_name='Dars boshlanish vaqti')),
                ('days', models.CharField(choices=[('odd', 'Toq kunlar (Du-Chor-Ju)'), ('even', 'Juft kunlar (Se-Pay-Sha)'), ('everyday', 'Har kuni'), ('weekend', 'Dam olish kunlari (Sha-Yak)')], default='odd', max_length=20, verbose_name='Dars kunlari')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='courses.course')),
            ],
        ),
    ]
